services:

  sonarqube:
    image: sonarqube:community

  sonarqubedb:
    image: postgres:latest

  sonarscanner:
    image: openjdk:17-jdk

  gitea:
    image: gitea/gitea:latest

  giteadb:
    image: postgres:latest

  jenkins:
    image: jenkins/jenkins:lts

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogdb:
    image: mongo:latest

  mongo-express:
    image: mongo-express:latest

  reactapp:
    build:
      context: ./Client/ecommerce-web-app    
    ports:
      - "3722:80"
    

volumes:
  sonarqubedb:
  giteadb:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  gitea_data:
