services:
  sonarqube:
    image: sonarqube:community

  sonarqubedb:
    image: postgres:latest

  gitea:
    image: gitea/gitea:latest

  giteadb:
    image: postgres:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  dotnet-sdk:
    image: mcr.microsoft.com/dotnet/sdk:8.0

  jenkins:
    image: jenkins/jenkins:lts


volumes:
  sonarqubedb:
  giteadb:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  gitea_data:
