version: '3'

services:
  sonarqubedb:
    container_name: sonarqubedb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonarqube
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - sonarqubedb:/var/lib/postgresql/data/

  giteadb:
    container_name: giteadb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitea
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - giteadb:/var/lib/postgresql/data/

  sonarqube:
    container_name: sonarqube
    depends_on:
      - sonarqubedb
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  gitea:
    container_name: gitea
    depends_on:
      - giteadb
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=giteadb:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
    volumes:
      - gitea_data:/data
    restart: always

  jenkins:
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  sonarqubedb:
  giteadb:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  gitea_data:
  jenkins_home: